root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/web ./cmd/web"
bin = "tmp/web"
include_ext = ["go", "tpl", "html", "css", "js", "md", "txt"]
exclude_dir = ["tmp", ".git"]

[pre_build]
commands = [
    "go fmt ./...",
    "go vet ./...",
]

[run]
